// All India Districts — Lightweight search & map pin lookup
// Contains all 802 districts with name, state, latitude, longitude
// Source: Census 2011 + Official 2023-2024 Gazette Reorganization Data

export interface IndiaDistrict {
  district: string;
  state: string;
  latitude: number;
  longitude: number;
}

export const ALL_INDIA_DISTRICTS: IndiaDistrict[] = [
  // ─── ANDHRA PRADESH (26 Districts) ──────────────────────
  { district: "Anantapur", state: "Andhra Pradesh", latitude: 14.68, longitude: 77.6 },
  { district: "Chittoor", state: "Andhra Pradesh", latitude: 13.22, longitude: 79.1 },
  { district: "East Godavari", state: "Andhra Pradesh", latitude: 17.0, longitude: 82.0 },
  { district: "Guntur", state: "Andhra Pradesh", latitude: 16.3, longitude: 80.45 },
  { district: "Krishna", state: "Andhra Pradesh", latitude: 16.6, longitude: 80.7 },
  { district: "Kurnool", state: "Andhra Pradesh", latitude: 15.83, longitude: 78.05 },
  { district: "Nellore", state: "Andhra Pradesh", latitude: 14.45, longitude: 79.99 },
  { district: "Prakasam", state: "Andhra Pradesh", latitude: 15.35, longitude: 79.55 },
  { district: "Srikakulam", state: "Andhra Pradesh", latitude: 18.3, longitude: 83.9 },
  { district: "Visakhapatnam", state: "Andhra Pradesh", latitude: 17.7, longitude: 83.3 },
  { district: "Vizianagaram", state: "Andhra Pradesh", latitude: 18.12, longitude: 83.42 },
  { district: "West Godavari", state: "Andhra Pradesh", latitude: 16.9, longitude: 81.3 },
  { district: "YSR Kadapa", state: "Andhra Pradesh", latitude: 14.47, longitude: 78.82 },
  { district: "Alluri Sitharama Raju", state: "Andhra Pradesh", latitude: 17.5, longitude: 82.2 },
  { district: "Anakapalli", state: "Andhra Pradesh", latitude: 17.69, longitude: 83.0 },
  { district: "Annamayya", state: "Andhra Pradesh", latitude: 14.0, longitude: 78.8 },
  { district: "Bapatla", state: "Andhra Pradesh", latitude: 15.9, longitude: 80.47 },
  { district: "Eluru", state: "Andhra Pradesh", latitude: 16.71, longitude: 81.1 },
  { district: "Kakinada", state: "Andhra Pradesh", latitude: 16.94, longitude: 82.24 },
  { district: "Konaseema", state: "Andhra Pradesh", latitude: 16.6, longitude: 82.1 },
  { district: "NTR", state: "Andhra Pradesh", latitude: 16.5, longitude: 80.6 },
  { district: "Nandyal", state: "Andhra Pradesh", latitude: 15.48, longitude: 78.48 },
  { district: "Palnadu", state: "Andhra Pradesh", latitude: 16.1, longitude: 79.7 },
  { district: "Parvathipuram Manyam", state: "Andhra Pradesh", latitude: 18.5, longitude: 83.4 },
  { district: "Sri Sathya Sai", state: "Andhra Pradesh", latitude: 14.2, longitude: 77.6 },
  { district: "Tirupati", state: "Andhra Pradesh", latitude: 13.63, longitude: 79.42 },

  // ─── ARUNACHAL PRADESH (26 Districts) ──────────────────
  { district: "Anjaw", state: "Arunachal Pradesh", latitude: 28.07, longitude: 96.84 },
  { district: "Changlang", state: "Arunachal Pradesh", latitude: 27.12, longitude: 95.73 },
  { district: "Dibang Valley", state: "Arunachal Pradesh", latitude: 28.7, longitude: 95.75 },
  { district: "East Kameng", state: "Arunachal Pradesh", latitude: 27.3, longitude: 93.0 },
  { district: "East Siang", state: "Arunachal Pradesh", latitude: 28.13, longitude: 95.2 },
  { district: "Kamle", state: "Arunachal Pradesh", latitude: 27.8, longitude: 94.0 },
  { district: "Kra Daadi", state: "Arunachal Pradesh", latitude: 27.95, longitude: 93.7 },
  { district: "Kurung Kumey", state: "Arunachal Pradesh", latitude: 28.0, longitude: 93.4 },
  { district: "Lepa Rada", state: "Arunachal Pradesh", latitude: 27.6, longitude: 93.8 },
  { district: "Lohit", state: "Arunachal Pradesh", latitude: 27.9, longitude: 96.2 },
  { district: "Longding", state: "Arunachal Pradesh", latitude: 26.9, longitude: 95.7 },
  { district: "Lower Dibang Valley", state: "Arunachal Pradesh", latitude: 28.0, longitude: 95.9 },
  { district: "Lower Siang", state: "Arunachal Pradesh", latitude: 28.0, longitude: 94.8 },
  { district: "Lower Subansiri", state: "Arunachal Pradesh", latitude: 27.6, longitude: 93.9 },
  { district: "Namsai", state: "Arunachal Pradesh", latitude: 27.68, longitude: 95.87 },
  { district: "Pakke-Kessang", state: "Arunachal Pradesh", latitude: 27.0, longitude: 93.1 },
  { district: "Papum Pare", state: "Arunachal Pradesh", latitude: 27.1, longitude: 93.7 },
  { district: "Shi Yomi", state: "Arunachal Pradesh", latitude: 28.5, longitude: 94.5 },
  { district: "Siang", state: "Arunachal Pradesh", latitude: 28.5, longitude: 95.0 },
  { district: "Tawang", state: "Arunachal Pradesh", latitude: 27.59, longitude: 91.86 },
  { district: "Tirap", state: "Arunachal Pradesh", latitude: 26.97, longitude: 95.52 },
  { district: "Upper Siang", state: "Arunachal Pradesh", latitude: 28.8, longitude: 95.3 },
  { district: "Upper Subansiri", state: "Arunachal Pradesh", latitude: 28.2, longitude: 94.2 },
  { district: "West Kameng", state: "Arunachal Pradesh", latitude: 27.3, longitude: 92.3 },
  { district: "West Siang", state: "Arunachal Pradesh", latitude: 28.4, longitude: 94.4 },
  { district: "Itanagar Capital Complex", state: "Arunachal Pradesh", latitude: 27.08, longitude: 93.61 },

  // ─── ASSAM (35 Districts) ──────────────────────────────
  { district: "Baksa", state: "Assam", latitude: 26.7, longitude: 91.25 },
  { district: "Barpeta", state: "Assam", latitude: 26.32, longitude: 91.0 },
  { district: "Biswanath", state: "Assam", latitude: 26.7, longitude: 93.1 },
  { district: "Bongaigaon", state: "Assam", latitude: 26.48, longitude: 90.56 },
  { district: "Cachar", state: "Assam", latitude: 24.78, longitude: 92.85 },
  { district: "Charaideo", state: "Assam", latitude: 26.9, longitude: 95.0 },
  { district: "Chirang", state: "Assam", latitude: 26.6, longitude: 90.4 },
  { district: "Darrang", state: "Assam", latitude: 26.45, longitude: 92.17 },
  { district: "Dhemaji", state: "Assam", latitude: 27.47, longitude: 94.57 },
  { district: "Dhubri", state: "Assam", latitude: 26.02, longitude: 89.98 },
  { district: "Dibrugarh", state: "Assam", latitude: 27.47, longitude: 94.91 },
  { district: "Dima Hasao", state: "Assam", latitude: 25.5, longitude: 93.0 },
  { district: "Goalpara", state: "Assam", latitude: 26.17, longitude: 90.63 },
  { district: "Golaghat", state: "Assam", latitude: 26.52, longitude: 93.97 },
  { district: "Hailakandi", state: "Assam", latitude: 24.68, longitude: 92.57 },
  { district: "Hojai", state: "Assam", latitude: 26.0, longitude: 92.9 },
  { district: "Jorhat", state: "Assam", latitude: 26.76, longitude: 94.22 },
  { district: "Kamrup", state: "Assam", latitude: 26.22, longitude: 91.57 },
  { district: "Kamrup Metropolitan", state: "Assam", latitude: 26.14, longitude: 91.74 },
  { district: "Karbi Anglong", state: "Assam", latitude: 25.9, longitude: 93.5 },
  { district: "Karimganj", state: "Assam", latitude: 24.87, longitude: 92.35 },
  { district: "Kokrajhar", state: "Assam", latitude: 26.41, longitude: 90.27 },
  { district: "Lakhimpur", state: "Assam", latitude: 27.24, longitude: 94.1 },
  { district: "Majuli", state: "Assam", latitude: 26.95, longitude: 94.17 },
  { district: "Morigaon", state: "Assam", latitude: 26.25, longitude: 92.34 },
  { district: "Nagaon", state: "Assam", latitude: 26.35, longitude: 92.69 },
  { district: "Nalbari", state: "Assam", latitude: 26.44, longitude: 91.44 },
  { district: "Sivasagar", state: "Assam", latitude: 26.98, longitude: 94.64 },
  { district: "Sonitpur", state: "Assam", latitude: 26.72, longitude: 92.98 },
  { district: "South Salmara-Mankachar", state: "Assam", latitude: 25.6, longitude: 89.9 },
  { district: "Tinsukia", state: "Assam", latitude: 27.49, longitude: 95.37 },
  { district: "Udalguri", state: "Assam", latitude: 26.75, longitude: 92.1 },
  { district: "West Karbi Anglong", state: "Assam", latitude: 25.9, longitude: 93.0 },
  { district: "Bajali", state: "Assam", latitude: 26.4, longitude: 91.3 },
  { district: "Tamulpur", state: "Assam", latitude: 26.6, longitude: 91.8 },

  // ─── BIHAR (38 Districts) ──────────────────────────────
  { district: "Araria", state: "Bihar", latitude: 26.15, longitude: 87.51 },
  { district: "Arwal", state: "Bihar", latitude: 25.24, longitude: 84.66 },
  { district: "Aurangabad", state: "Bihar", latitude: 24.75, longitude: 84.37 },
  { district: "Banka", state: "Bihar", latitude: 24.89, longitude: 86.92 },
  { district: "Begusarai", state: "Bihar", latitude: 25.42, longitude: 86.13 },
  { district: "Bhagalpur", state: "Bihar", latitude: 25.24, longitude: 86.97 },
  { district: "Bhojpur", state: "Bihar", latitude: 25.47, longitude: 84.52 },
  { district: "Buxar", state: "Bihar", latitude: 25.56, longitude: 83.98 },
  { district: "Darbhanga", state: "Bihar", latitude: 26.12, longitude: 85.9 },
  { district: "Gaya", state: "Bihar", latitude: 24.8, longitude: 84.99 },
  { district: "Gopalganj", state: "Bihar", latitude: 26.47, longitude: 84.44 },
  { district: "Jamui", state: "Bihar", latitude: 24.93, longitude: 86.22 },
  { district: "Jehanabad", state: "Bihar", latitude: 25.21, longitude: 84.99 },
  { district: "Kaimur", state: "Bihar", latitude: 25.04, longitude: 83.61 },
  { district: "Katihar", state: "Bihar", latitude: 25.54, longitude: 87.57 },
  { district: "Khagaria", state: "Bihar", latitude: 25.5, longitude: 86.47 },
  { district: "Kishanganj", state: "Bihar", latitude: 26.09, longitude: 87.95 },
  { district: "Lakhisarai", state: "Bihar", latitude: 25.16, longitude: 86.09 },
  { district: "Madhepura", state: "Bihar", latitude: 25.92, longitude: 86.79 },
  { district: "Madhubani", state: "Bihar", latitude: 26.36, longitude: 86.07 },
  { district: "Munger", state: "Bihar", latitude: 25.38, longitude: 86.47 },
  { district: "Muzaffarpur", state: "Bihar", latitude: 26.12, longitude: 85.39 },
  { district: "Nalanda", state: "Bihar", latitude: 25.13, longitude: 85.44 },
  { district: "Nawada", state: "Bihar", latitude: 24.89, longitude: 85.53 },
  { district: "Patna", state: "Bihar", latitude: 25.61, longitude: 85.14 },
  { district: "Purnia", state: "Bihar", latitude: 25.78, longitude: 87.47 },
  { district: "Rohtas", state: "Bihar", latitude: 24.97, longitude: 84.01 },
  { district: "Saharsa", state: "Bihar", latitude: 25.88, longitude: 86.6 },
  { district: "Samastipur", state: "Bihar", latitude: 25.86, longitude: 85.78 },
  { district: "Saran", state: "Bihar", latitude: 25.87, longitude: 84.78 },
  { district: "Sheikhpura", state: "Bihar", latitude: 25.14, longitude: 85.84 },
  { district: "Sheohar", state: "Bihar", latitude: 26.52, longitude: 85.3 },
  { district: "Sitamarhi", state: "Bihar", latitude: 26.59, longitude: 85.49 },
  { district: "Siwan", state: "Bihar", latitude: 26.22, longitude: 84.36 },
  { district: "Supaul", state: "Bihar", latitude: 26.12, longitude: 86.6 },
  { district: "Vaishali", state: "Bihar", latitude: 25.69, longitude: 85.22 },
  { district: "West Champaran", state: "Bihar", latitude: 26.87, longitude: 84.53 },
  { district: "East Champaran", state: "Bihar", latitude: 26.65, longitude: 84.85 },

  // ─── CHHATTISGARH (33 Districts) ───────────────────────
  { district: "Balod", state: "Chhattisgarh", latitude: 20.73, longitude: 81.2 },
  { district: "Baloda Bazar", state: "Chhattisgarh", latitude: 21.66, longitude: 82.16 },
  { district: "Balrampur", state: "Chhattisgarh", latitude: 23.63, longitude: 83.6 },
  { district: "Bastar", state: "Chhattisgarh", latitude: 19.07, longitude: 82.02 },
  { district: "Bemetara", state: "Chhattisgarh", latitude: 21.72, longitude: 81.53 },
  { district: "Bijapur", state: "Chhattisgarh", latitude: 18.84, longitude: 80.77 },
  { district: "Bilaspur", state: "Chhattisgarh", latitude: 22.08, longitude: 82.15 },
  { district: "Dantewada", state: "Chhattisgarh", latitude: 18.9, longitude: 81.35 },
  { district: "Dhamtari", state: "Chhattisgarh", latitude: 20.71, longitude: 81.55 },
  { district: "Durg", state: "Chhattisgarh", latitude: 21.19, longitude: 81.28 },
  { district: "Gariaband", state: "Chhattisgarh", latitude: 20.63, longitude: 82.06 },
  { district: "Gaurela-Pendra-Marwahi", state: "Chhattisgarh", latitude: 22.9, longitude: 81.7 },
  { district: "Janjgir-Champa", state: "Chhattisgarh", latitude: 22.01, longitude: 82.57 },
  { district: "Jashpur", state: "Chhattisgarh", latitude: 22.89, longitude: 84.14 },
  { district: "Kabirdham", state: "Chhattisgarh", latitude: 22.1, longitude: 81.2 },
  { district: "Kanker", state: "Chhattisgarh", latitude: 20.27, longitude: 81.49 },
  { district: "Kondagaon", state: "Chhattisgarh", latitude: 19.6, longitude: 81.66 },
  { district: "Korba", state: "Chhattisgarh", latitude: 22.35, longitude: 82.68 },
  { district: "Koriya", state: "Chhattisgarh", latitude: 23.25, longitude: 82.58 },
  { district: "Mahasamund", state: "Chhattisgarh", latitude: 21.11, longitude: 82.1 },
  { district: "Mungeli", state: "Chhattisgarh", latitude: 22.07, longitude: 81.69 },
  { district: "Narayanpur", state: "Chhattisgarh", latitude: 19.73, longitude: 81.25 },
  { district: "Raigarh", state: "Chhattisgarh", latitude: 21.9, longitude: 83.4 },
  { district: "Raipur", state: "Chhattisgarh", latitude: 21.25, longitude: 81.63 },
  { district: "Rajnandgaon", state: "Chhattisgarh", latitude: 21.1, longitude: 81.03 },
  { district: "Sukma", state: "Chhattisgarh", latitude: 18.4, longitude: 81.66 },
  { district: "Surajpur", state: "Chhattisgarh", latitude: 23.21, longitude: 82.87 },
  { district: "Surguja", state: "Chhattisgarh", latitude: 23.12, longitude: 83.19 },
  { district: "Khairagarh-Chhuikhadan-Gandai", state: "Chhattisgarh", latitude: 21.4, longitude: 80.9 },
  { district: "Manendragarh-Chirmiri-Bharatpur", state: "Chhattisgarh", latitude: 23.4, longitude: 82.2 },
  { district: "Mohla-Manpur-Ambagarh Chowki", state: "Chhattisgarh", latitude: 20.7, longitude: 80.6 },
  { district: "Sarangarh-Bilaigarh", state: "Chhattisgarh", latitude: 21.6, longitude: 83.1 },
  { district: "Shakti", state: "Chhattisgarh", latitude: 22.1, longitude: 82.7 },

  // ─── GOA (2 Districts) ────────────────────────────────
  { district: "North Goa", state: "Goa", latitude: 15.53, longitude: 73.95 },
  { district: "South Goa", state: "Goa", latitude: 15.2, longitude: 74.0 },

  // ─── GUJARAT (33 Districts) ────────────────────────────
  { district: "Ahmedabad", state: "Gujarat", latitude: 23.02, longitude: 72.57 },
  { district: "Amreli", state: "Gujarat", latitude: 21.6, longitude: 71.22 },
  { district: "Anand", state: "Gujarat", latitude: 22.56, longitude: 72.95 },
  { district: "Aravalli", state: "Gujarat", latitude: 23.7, longitude: 73.3 },
  { district: "Banaskantha", state: "Gujarat", latitude: 24.17, longitude: 72.43 },
  { district: "Bharuch", state: "Gujarat", latitude: 21.71, longitude: 72.99 },
  { district: "Bhavnagar", state: "Gujarat", latitude: 21.77, longitude: 72.15 },
  { district: "Botad", state: "Gujarat", latitude: 22.17, longitude: 71.67 },
  { district: "Chhota Udaipur", state: "Gujarat", latitude: 22.3, longitude: 74.02 },
  { district: "Dahod", state: "Gujarat", latitude: 22.84, longitude: 74.25 },
  { district: "Devbhumi Dwarka", state: "Gujarat", latitude: 22.2, longitude: 69.1 },
  { district: "Gandhinagar", state: "Gujarat", latitude: 23.22, longitude: 72.64 },
  { district: "Gir Somnath", state: "Gujarat", latitude: 20.9, longitude: 70.5 },
  { district: "Jamnagar", state: "Gujarat", latitude: 22.47, longitude: 70.07 },
  { district: "Junagadh", state: "Gujarat", latitude: 21.52, longitude: 70.46 },
  { district: "Kutch", state: "Gujarat", latitude: 23.73, longitude: 69.86 },
  { district: "Kheda", state: "Gujarat", latitude: 22.75, longitude: 72.68 },
  { district: "Mahisagar", state: "Gujarat", latitude: 23.1, longitude: 73.6 },
  { district: "Mehsana", state: "Gujarat", latitude: 23.59, longitude: 72.38 },
  { district: "Morbi", state: "Gujarat", latitude: 22.82, longitude: 70.83 },
  { district: "Narmada", state: "Gujarat", latitude: 21.87, longitude: 73.5 },
  { district: "Navsari", state: "Gujarat", latitude: 20.95, longitude: 72.92 },
  { district: "Panchmahal", state: "Gujarat", latitude: 22.75, longitude: 73.6 },
  { district: "Patan", state: "Gujarat", latitude: 23.85, longitude: 72.13 },
  { district: "Porbandar", state: "Gujarat", latitude: 21.64, longitude: 69.61 },
  { district: "Rajkot", state: "Gujarat", latitude: 22.3, longitude: 70.78 },
  { district: "Sabarkantha", state: "Gujarat", latitude: 23.63, longitude: 73.0 },
  { district: "Surat", state: "Gujarat", latitude: 21.17, longitude: 72.83 },
  { district: "Surendranagar", state: "Gujarat", latitude: 22.73, longitude: 71.65 },
  { district: "Tapi", state: "Gujarat", latitude: 21.1, longitude: 73.4 },
  { district: "Vadodara", state: "Gujarat", latitude: 22.31, longitude: 73.19 },
  { district: "Valsad", state: "Gujarat", latitude: 20.6, longitude: 72.93 },
  { district: "Dang", state: "Gujarat", latitude: 20.75, longitude: 73.75 },

  // ─── HARYANA (22 Districts) ────────────────────────────
  { district: "Ambala", state: "Haryana", latitude: 30.38, longitude: 76.78 },
  { district: "Bhiwani", state: "Haryana", latitude: 28.79, longitude: 76.13 },
  { district: "Charkhi Dadri", state: "Haryana", latitude: 28.59, longitude: 76.27 },
  { district: "Faridabad", state: "Haryana", latitude: 28.41, longitude: 77.31 },
  { district: "Fatehabad", state: "Haryana", latitude: 29.52, longitude: 75.45 },
  { district: "Gurugram", state: "Haryana", latitude: 28.46, longitude: 77.03 },
  { district: "Hisar", state: "Haryana", latitude: 29.17, longitude: 75.72 },
  { district: "Jhajjar", state: "Haryana", latitude: 28.61, longitude: 76.66 },
  { district: "Jind", state: "Haryana", latitude: 29.32, longitude: 76.31 },
  { district: "Kaithal", state: "Haryana", latitude: 29.8, longitude: 76.4 },
  { district: "Karnal", state: "Haryana", latitude: 29.69, longitude: 76.98 },
  { district: "Kurukshetra", state: "Haryana", latitude: 29.97, longitude: 76.84 },
  { district: "Mahendragarh", state: "Haryana", latitude: 28.28, longitude: 76.15 },
  { district: "Nuh", state: "Haryana", latitude: 28.1, longitude: 77.0 },
  { district: "Palwal", state: "Haryana", latitude: 28.14, longitude: 77.33 },
  { district: "Panchkula", state: "Haryana", latitude: 30.69, longitude: 76.86 },
  { district: "Panipat", state: "Haryana", latitude: 29.39, longitude: 76.97 },
  { district: "Rewari", state: "Haryana", latitude: 28.19, longitude: 76.62 },
  { district: "Rohtak", state: "Haryana", latitude: 28.89, longitude: 76.59 },
  { district: "Sirsa", state: "Haryana", latitude: 29.53, longitude: 75.03 },
  { district: "Sonipat", state: "Haryana", latitude: 28.99, longitude: 77.02 },
  { district: "Yamunanagar", state: "Haryana", latitude: 30.13, longitude: 77.28 },

  // ─── HIMACHAL PRADESH (12 Districts) ───────────────────
  { district: "Bilaspur", state: "Himachal Pradesh", latitude: 31.34, longitude: 76.76 },
  { district: "Chamba", state: "Himachal Pradesh", latitude: 32.56, longitude: 76.13 },
  { district: "Hamirpur", state: "Himachal Pradesh", latitude: 31.68, longitude: 76.52 },
  { district: "Kangra", state: "Himachal Pradesh", latitude: 32.1, longitude: 76.27 },
  { district: "Kinnaur", state: "Himachal Pradesh", latitude: 31.58, longitude: 78.17 },
  { district: "Kullu", state: "Himachal Pradesh", latitude: 31.96, longitude: 77.11 },
  { district: "Lahaul and Spiti", state: "Himachal Pradesh", latitude: 32.57, longitude: 77.04 },
  { district: "Mandi", state: "Himachal Pradesh", latitude: 31.72, longitude: 76.93 },
  { district: "Shimla", state: "Himachal Pradesh", latitude: 31.1, longitude: 77.17 },
  { district: "Sirmaur", state: "Himachal Pradesh", latitude: 30.57, longitude: 77.3 },
  { district: "Solan", state: "Himachal Pradesh", latitude: 30.91, longitude: 77.1 },
  { district: "Una", state: "Himachal Pradesh", latitude: 31.47, longitude: 76.27 },

  // ─── JHARKHAND (24 Districts) ──────────────────────────
  { district: "Bokaro", state: "Jharkhand", latitude: 23.67, longitude: 85.98 },
  { district: "Chatra", state: "Jharkhand", latitude: 24.21, longitude: 84.87 },
  { district: "Deoghar", state: "Jharkhand", latitude: 24.49, longitude: 86.7 },
  { district: "Dhanbad", state: "Jharkhand", latitude: 23.79, longitude: 86.43 },
  { district: "Dumka", state: "Jharkhand", latitude: 24.27, longitude: 87.25 },
  { district: "East Singhbhum", state: "Jharkhand", latitude: 22.8, longitude: 86.2 },
  { district: "Garhwa", state: "Jharkhand", latitude: 24.16, longitude: 83.81 },
  { district: "Giridih", state: "Jharkhand", latitude: 24.19, longitude: 86.3 },
  { district: "Godda", state: "Jharkhand", latitude: 24.83, longitude: 87.21 },
  { district: "Gumla", state: "Jharkhand", latitude: 23.04, longitude: 84.54 },
  { district: "Hazaribagh", state: "Jharkhand", latitude: 23.99, longitude: 85.36 },
  { district: "Jamtara", state: "Jharkhand", latitude: 23.96, longitude: 86.81 },
  { district: "Khunti", state: "Jharkhand", latitude: 23.07, longitude: 85.28 },
  { district: "Koderma", state: "Jharkhand", latitude: 24.47, longitude: 85.59 },
  { district: "Latehar", state: "Jharkhand", latitude: 23.74, longitude: 84.5 },
  { district: "Lohardaga", state: "Jharkhand", latitude: 23.43, longitude: 84.68 },
  { district: "Pakur", state: "Jharkhand", latitude: 24.64, longitude: 87.84 },
  { district: "Palamu", state: "Jharkhand", latitude: 24.03, longitude: 84.07 },
  { district: "Ramgarh", state: "Jharkhand", latitude: 23.63, longitude: 85.52 },
  { district: "Ranchi", state: "Jharkhand", latitude: 23.36, longitude: 85.33 },
  { district: "Sahibganj", state: "Jharkhand", latitude: 25.24, longitude: 87.64 },
  { district: "Saraikela-Kharsawan", state: "Jharkhand", latitude: 22.7, longitude: 85.9 },
  { district: "Simdega", state: "Jharkhand", latitude: 22.62, longitude: 84.5 },
  { district: "West Singhbhum", state: "Jharkhand", latitude: 22.3, longitude: 85.6 },

  // ─── KARNATAKA (31 Districts) ──────────────────────────
  { district: "Bagalkot", state: "Karnataka", latitude: 16.18, longitude: 75.7 },
  { district: "Ballari", state: "Karnataka", latitude: 15.14, longitude: 76.92 },
  { district: "Belagavi", state: "Karnataka", latitude: 15.85, longitude: 74.5 },
  { district: "Bengaluru Rural", state: "Karnataka", latitude: 13.22, longitude: 77.71 },
  { district: "Bengaluru Urban", state: "Karnataka", latitude: 12.97, longitude: 77.59 },
  { district: "Bidar", state: "Karnataka", latitude: 17.92, longitude: 77.52 },
  { district: "Chamarajanagar", state: "Karnataka", latitude: 11.92, longitude: 76.94 },
  { district: "Chikkaballapur", state: "Karnataka", latitude: 13.44, longitude: 77.73 },
  { district: "Chikkamagaluru", state: "Karnataka", latitude: 13.32, longitude: 75.77 },
  { district: "Chitradurga", state: "Karnataka", latitude: 14.23, longitude: 76.4 },
  { district: "Dakshina Kannada", state: "Karnataka", latitude: 12.87, longitude: 75.37 },
  { district: "Davanagere", state: "Karnataka", latitude: 14.47, longitude: 75.92 },
  { district: "Dharwad", state: "Karnataka", latitude: 15.46, longitude: 75.01 },
  { district: "Gadag", state: "Karnataka", latitude: 15.43, longitude: 75.63 },
  { district: "Hassan", state: "Karnataka", latitude: 13.0, longitude: 76.1 },
  { district: "Haveri", state: "Karnataka", latitude: 14.8, longitude: 75.4 },
  { district: "Kalaburagi", state: "Karnataka", latitude: 17.33, longitude: 76.83 },
  { district: "Kodagu", state: "Karnataka", latitude: 12.42, longitude: 75.74 },
  { district: "Kolar", state: "Karnataka", latitude: 13.14, longitude: 78.13 },
  { district: "Koppal", state: "Karnataka", latitude: 15.35, longitude: 76.15 },
  { district: "Mandya", state: "Karnataka", latitude: 12.52, longitude: 76.9 },
  { district: "Mysuru", state: "Karnataka", latitude: 12.3, longitude: 76.64 },
  { district: "Raichur", state: "Karnataka", latitude: 16.2, longitude: 77.37 },
  { district: "Ramanagara", state: "Karnataka", latitude: 12.71, longitude: 77.28 },
  { district: "Shivamogga", state: "Karnataka", latitude: 13.93, longitude: 75.57 },
  { district: "Tumakuru", state: "Karnataka", latitude: 13.34, longitude: 77.1 },
  { district: "Udupi", state: "Karnataka", latitude: 13.34, longitude: 74.75 },
  { district: "Uttara Kannada", state: "Karnataka", latitude: 14.67, longitude: 74.68 },
  { district: "Vijayapura", state: "Karnataka", latitude: 16.83, longitude: 75.72 },
  { district: "Yadgir", state: "Karnataka", latitude: 16.77, longitude: 77.14 },
  { district: "Vijayanagara", state: "Karnataka", latitude: 15.33, longitude: 76.47 },

  // ─── KERALA (14 Districts) ─────────────────────────────
  { district: "Alappuzha", state: "Kerala", latitude: 9.49, longitude: 76.34 },
  { district: "Ernakulam", state: "Kerala", latitude: 10.0, longitude: 76.3 },
  { district: "Idukki", state: "Kerala", latitude: 9.85, longitude: 76.97 },
  { district: "Kannur", state: "Kerala", latitude: 11.87, longitude: 75.37 },
  { district: "Kasaragod", state: "Kerala", latitude: 12.5, longitude: 74.99 },
  { district: "Kollam", state: "Kerala", latitude: 8.89, longitude: 76.6 },
  { district: "Kottayam", state: "Kerala", latitude: 9.59, longitude: 76.52 },
  { district: "Kozhikode", state: "Kerala", latitude: 11.25, longitude: 75.77 },
  { district: "Malappuram", state: "Kerala", latitude: 11.07, longitude: 76.07 },
  { district: "Palakkad", state: "Kerala", latitude: 10.77, longitude: 76.65 },
  { district: "Pathanamthitta", state: "Kerala", latitude: 9.27, longitude: 76.79 },
  { district: "Thiruvananthapuram", state: "Kerala", latitude: 8.52, longitude: 76.94 },
  { district: "Thrissur", state: "Kerala", latitude: 10.52, longitude: 76.21 },
  { district: "Wayanad", state: "Kerala", latitude: 11.69, longitude: 76.07 },

  // ─── MADHYA PRADESH (53 Districts) ─────────────────────
  { district: "Agar Malwa", state: "Madhya Pradesh", latitude: 23.71, longitude: 76.01 },
  { district: "Alirajpur", state: "Madhya Pradesh", latitude: 22.31, longitude: 74.36 },
  { district: "Anuppur", state: "Madhya Pradesh", latitude: 23.08, longitude: 81.7 },
  { district: "Ashoknagar", state: "Madhya Pradesh", latitude: 24.58, longitude: 77.73 },
  { district: "Balaghat", state: "Madhya Pradesh", latitude: 21.81, longitude: 80.19 },
  { district: "Barwani", state: "Madhya Pradesh", latitude: 22.04, longitude: 74.9 },
  { district: "Betul", state: "Madhya Pradesh", latitude: 21.91, longitude: 77.9 },
  { district: "Bhind", state: "Madhya Pradesh", latitude: 26.56, longitude: 78.78 },
  { district: "Bhopal", state: "Madhya Pradesh", latitude: 23.26, longitude: 77.41 },
  { district: "Burhanpur", state: "Madhya Pradesh", latitude: 21.3, longitude: 76.23 },
  { district: "Chhatarpur", state: "Madhya Pradesh", latitude: 24.92, longitude: 79.59 },
  { district: "Chhindwara", state: "Madhya Pradesh", latitude: 22.06, longitude: 78.94 },
  { district: "Damoh", state: "Madhya Pradesh", latitude: 23.84, longitude: 79.44 },
  { district: "Datia", state: "Madhya Pradesh", latitude: 25.67, longitude: 78.46 },
  { district: "Dewas", state: "Madhya Pradesh", latitude: 22.97, longitude: 76.05 },
  { district: "Dhar", state: "Madhya Pradesh", latitude: 22.6, longitude: 75.3 },
  { district: "Dindori", state: "Madhya Pradesh", latitude: 22.95, longitude: 81.08 },
  { district: "Guna", state: "Madhya Pradesh", latitude: 24.65, longitude: 77.32 },
  { district: "Gwalior", state: "Madhya Pradesh", latitude: 26.22, longitude: 78.18 },
  { district: "Harda", state: "Madhya Pradesh", latitude: 22.34, longitude: 77.1 },
  { district: "Hoshangabad", state: "Madhya Pradesh", latitude: 22.75, longitude: 77.73 },
  { district: "Indore", state: "Madhya Pradesh", latitude: 22.72, longitude: 75.86 },
  { district: "Jabalpur", state: "Madhya Pradesh", latitude: 23.18, longitude: 79.95 },
  { district: "Jhabua", state: "Madhya Pradesh", latitude: 22.77, longitude: 74.59 },
  { district: "Katni", state: "Madhya Pradesh", latitude: 23.83, longitude: 80.39 },
  { district: "Khandwa", state: "Madhya Pradesh", latitude: 21.83, longitude: 76.35 },
  { district: "Khargone", state: "Madhya Pradesh", latitude: 21.83, longitude: 75.62 },
  { district: "Maihar", state: "Madhya Pradesh", latitude: 24.26, longitude: 80.76 },
  { district: "Mandla", state: "Madhya Pradesh", latitude: 22.6, longitude: 80.38 },
  { district: "Mandsaur", state: "Madhya Pradesh", latitude: 24.07, longitude: 75.08 },
  { district: "Morena", state: "Madhya Pradesh", latitude: 26.5, longitude: 77.99 },
  { district: "Narsinghpur", state: "Madhya Pradesh", latitude: 22.95, longitude: 79.19 },
  { district: "Neemuch", state: "Madhya Pradesh", latitude: 24.47, longitude: 74.87 },
  { district: "Niwari", state: "Madhya Pradesh", latitude: 25.13, longitude: 78.4 },
  { district: "Panna", state: "Madhya Pradesh", latitude: 24.72, longitude: 80.19 },
  { district: "Raisen", state: "Madhya Pradesh", latitude: 23.33, longitude: 77.79 },
  { district: "Rajgarh", state: "Madhya Pradesh", latitude: 24.0, longitude: 76.62 },
  { district: "Ratlam", state: "Madhya Pradesh", latitude: 23.33, longitude: 75.04 },
  { district: "Rewa", state: "Madhya Pradesh", latitude: 24.53, longitude: 81.3 },
  { district: "Sagar", state: "Madhya Pradesh", latitude: 23.84, longitude: 78.74 },
  { district: "Satna", state: "Madhya Pradesh", latitude: 24.58, longitude: 80.83 },
  { district: "Sehore", state: "Madhya Pradesh", latitude: 23.21, longitude: 77.09 },
  { district: "Seoni", state: "Madhya Pradesh", latitude: 22.08, longitude: 79.54 },
  { district: "Shahdol", state: "Madhya Pradesh", latitude: 23.3, longitude: 81.35 },
  { district: "Shajapur", state: "Madhya Pradesh", latitude: 23.43, longitude: 76.27 },
  { district: "Sheopur", state: "Madhya Pradesh", latitude: 25.67, longitude: 76.7 },
  { district: "Shivpuri", state: "Madhya Pradesh", latitude: 25.43, longitude: 77.66 },
  { district: "Sidhi", state: "Madhya Pradesh", latitude: 24.41, longitude: 81.88 },
  { district: "Singrauli", state: "Madhya Pradesh", latitude: 24.2, longitude: 82.65 },
  { district: "Tikamgarh", state: "Madhya Pradesh", latitude: 24.74, longitude: 78.83 },
  { district: "Ujjain", state: "Madhya Pradesh", latitude: 23.18, longitude: 75.77 },
  { district: "Umaria", state: "Madhya Pradesh", latitude: 23.52, longitude: 80.83 },
  { district: "Vidisha", state: "Madhya Pradesh", latitude: 23.53, longitude: 77.81 },

  // ─── MAHARASHTRA (36 Districts) ────────────────────────
  { district: "Ahmednagar", state: "Maharashtra", latitude: 19.09, longitude: 74.74 },
  { district: "Akola", state: "Maharashtra", latitude: 20.71, longitude: 77.0 },
  { district: "Amravati", state: "Maharashtra", latitude: 20.93, longitude: 77.75 },
  { district: "Beed", state: "Maharashtra", latitude: 18.99, longitude: 75.76 },
  { district: "Bhandara", state: "Maharashtra", latitude: 21.17, longitude: 79.65 },
  { district: "Buldhana", state: "Maharashtra", latitude: 20.53, longitude: 76.18 },
  { district: "Chandrapur", state: "Maharashtra", latitude: 19.95, longitude: 79.3 },
  { district: "Dhule", state: "Maharashtra", latitude: 20.9, longitude: 74.78 },
  { district: "Gadchiroli", state: "Maharashtra", latitude: 20.18, longitude: 80.0 },
  { district: "Gondia", state: "Maharashtra", latitude: 21.46, longitude: 80.2 },
  { district: "Hingoli", state: "Maharashtra", latitude: 19.72, longitude: 77.15 },
  { district: "Jalgaon", state: "Maharashtra", latitude: 21.01, longitude: 75.56 },
  { district: "Jalna", state: "Maharashtra", latitude: 19.84, longitude: 75.88 },
  { district: "Kolhapur", state: "Maharashtra", latitude: 16.7, longitude: 74.24 },
  { district: "Latur", state: "Maharashtra", latitude: 18.4, longitude: 76.57 },
  { district: "Mumbai", state: "Maharashtra", latitude: 19.08, longitude: 72.88 },
  { district: "Mumbai Suburban", state: "Maharashtra", latitude: 19.18, longitude: 72.85 },
  { district: "Nagpur", state: "Maharashtra", latitude: 21.15, longitude: 79.09 },
  { district: "Nanded", state: "Maharashtra", latitude: 19.15, longitude: 77.32 },
  { district: "Nandurbar", state: "Maharashtra", latitude: 21.37, longitude: 74.24 },
  { district: "Nashik", state: "Maharashtra", latitude: 20.0, longitude: 73.79 },
  { district: "Osmanabad", state: "Maharashtra", latitude: 18.19, longitude: 76.04 },
  { district: "Palghar", state: "Maharashtra", latitude: 19.69, longitude: 72.77 },
  { district: "Parbhani", state: "Maharashtra", latitude: 19.27, longitude: 76.78 },
  { district: "Pune", state: "Maharashtra", latitude: 18.52, longitude: 73.86 },
  { district: "Raigad", state: "Maharashtra", latitude: 18.52, longitude: 73.12 },
  { district: "Ratnagiri", state: "Maharashtra", latitude: 16.99, longitude: 73.3 },
  { district: "Sangli", state: "Maharashtra", latitude: 16.85, longitude: 74.56 },
  { district: "Satara", state: "Maharashtra", latitude: 17.68, longitude: 74.0 },
  { district: "Sindhudurg", state: "Maharashtra", latitude: 16.0, longitude: 73.46 },
  { district: "Solapur", state: "Maharashtra", latitude: 17.67, longitude: 75.9 },
  { district: "Thane", state: "Maharashtra", latitude: 19.2, longitude: 73.0 },
  { district: "Wardha", state: "Maharashtra", latitude: 20.74, longitude: 78.6 },
  { district: "Washim", state: "Maharashtra", latitude: 20.11, longitude: 77.13 },
  { district: "Yavatmal", state: "Maharashtra", latitude: 20.39, longitude: 78.12 },
  { district: "Chhatrapati Sambhajinagar", state: "Maharashtra", latitude: 19.88, longitude: 75.34 },

  // ─── MANIPUR (16 Districts) ────────────────────────────
  { district: "Bishnupur", state: "Manipur", latitude: 24.62, longitude: 93.78 },
  { district: "Chandel", state: "Manipur", latitude: 24.33, longitude: 93.97 },
  { district: "Churachandpur", state: "Manipur", latitude: 24.33, longitude: 93.68 },
  { district: "Imphal East", state: "Manipur", latitude: 24.82, longitude: 93.95 },
  { district: "Imphal West", state: "Manipur", latitude: 24.82, longitude: 93.92 },
  { district: "Jiribam", state: "Manipur", latitude: 24.8, longitude: 93.12 },
  { district: "Kakching", state: "Manipur", latitude: 24.5, longitude: 93.98 },
  { district: "Kamjong", state: "Manipur", latitude: 25.4, longitude: 94.5 },
  { district: "Kangpokpi", state: "Manipur", latitude: 25.1, longitude: 93.9 },
  { district: "Noney", state: "Manipur", latitude: 25.0, longitude: 93.5 },
  { district: "Pherzawl", state: "Manipur", latitude: 24.5, longitude: 93.3 },
  { district: "Senapati", state: "Manipur", latitude: 25.27, longitude: 94.02 },
  { district: "Tamenglong", state: "Manipur", latitude: 25.0, longitude: 93.5 },
  { district: "Tengnoupal", state: "Manipur", latitude: 24.2, longitude: 94.1 },
  { district: "Thoubal", state: "Manipur", latitude: 24.63, longitude: 94.0 },
  { district: "Ukhrul", state: "Manipur", latitude: 25.12, longitude: 94.37 },

  // ─── MEGHALAYA (12 Districts) ──────────────────────────
  { district: "East Garo Hills", state: "Meghalaya", latitude: 25.5, longitude: 90.6 },
  { district: "East Jaintia Hills", state: "Meghalaya", latitude: 25.3, longitude: 92.4 },
  { district: "East Khasi Hills", state: "Meghalaya", latitude: 25.57, longitude: 91.88 },
  { district: "North Garo Hills", state: "Meghalaya", latitude: 25.9, longitude: 90.6 },
  { district: "Ri Bhoi", state: "Meghalaya", latitude: 25.8, longitude: 91.8 },
  { district: "South Garo Hills", state: "Meghalaya", latitude: 25.3, longitude: 90.6 },
  { district: "South West Garo Hills", state: "Meghalaya", latitude: 25.4, longitude: 90.3 },
  { district: "South West Khasi Hills", state: "Meghalaya", latitude: 25.4, longitude: 91.3 },
  { district: "West Garo Hills", state: "Meghalaya", latitude: 25.5, longitude: 90.2 },
  { district: "West Jaintia Hills", state: "Meghalaya", latitude: 25.4, longitude: 92.2 },
  { district: "West Khasi Hills", state: "Meghalaya", latitude: 25.5, longitude: 91.3 },
  { district: "Eastern West Khasi Hills", state: "Meghalaya", latitude: 25.5, longitude: 91.5 },

  // ─── MIZORAM (11 Districts) ────────────────────────────
  { district: "Aizawl", state: "Mizoram", latitude: 23.73, longitude: 92.72 },
  { district: "Champhai", state: "Mizoram", latitude: 23.47, longitude: 93.33 },
  { district: "Hnahthial", state: "Mizoram", latitude: 22.4, longitude: 92.9 },
  { district: "Khawzawl", state: "Mizoram", latitude: 23.3, longitude: 93.2 },
  { district: "Kolasib", state: "Mizoram", latitude: 24.22, longitude: 92.68 },
  { district: "Lawngtlai", state: "Mizoram", latitude: 22.53, longitude: 92.9 },
  { district: "Lunglei", state: "Mizoram", latitude: 22.88, longitude: 92.74 },
  { district: "Mamit", state: "Mizoram", latitude: 23.92, longitude: 92.49 },
  { district: "Saiha", state: "Mizoram", latitude: 22.49, longitude: 92.97 },
  { district: "Saitual", state: "Mizoram", latitude: 23.8, longitude: 93.1 },
  { district: "Serchhip", state: "Mizoram", latitude: 23.3, longitude: 92.85 },

  // ─── NAGALAND (16 Districts) ───────────────────────────
  { district: "Chümoukedima", state: "Nagaland", latitude: 25.85, longitude: 93.7 },
  { district: "Dimapur", state: "Nagaland", latitude: 25.91, longitude: 93.73 },
  { district: "Kiphire", state: "Nagaland", latitude: 25.88, longitude: 95.12 },
  { district: "Kohima", state: "Nagaland", latitude: 25.67, longitude: 94.12 },
  { district: "Longleng", state: "Nagaland", latitude: 26.27, longitude: 94.87 },
  { district: "Mokokchung", state: "Nagaland", latitude: 26.33, longitude: 94.52 },
  { district: "Mon", state: "Nagaland", latitude: 26.7, longitude: 94.92 },
  { district: "Niuland", state: "Nagaland", latitude: 25.7, longitude: 93.8 },
  { district: "Noklak", state: "Nagaland", latitude: 26.5, longitude: 95.1 },
  { district: "Peren", state: "Nagaland", latitude: 25.52, longitude: 93.73 },
  { district: "Phek", state: "Nagaland", latitude: 25.67, longitude: 94.47 },
  { district: "Shamator", state: "Nagaland", latitude: 25.9, longitude: 95.0 },
  { district: "Tseminyü", state: "Nagaland", latitude: 25.9, longitude: 94.3 },
  { district: "Tuensang", state: "Nagaland", latitude: 26.27, longitude: 94.83 },
  { district: "Wokha", state: "Nagaland", latitude: 26.1, longitude: 94.27 },
  { district: "Zunheboto", state: "Nagaland", latitude: 25.97, longitude: 94.52 },

  // ─── ODISHA (30 Districts) ─────────────────────────────
  { district: "Angul", state: "Odisha", latitude: 20.84, longitude: 85.1 },
  { district: "Balangir", state: "Odisha", latitude: 20.72, longitude: 83.49 },
  { district: "Balasore", state: "Odisha", latitude: 21.49, longitude: 86.93 },
  { district: "Bargarh", state: "Odisha", latitude: 21.33, longitude: 83.62 },
  { district: "Bhadrak", state: "Odisha", latitude: 21.06, longitude: 86.52 },
  { district: "Boudh", state: "Odisha", latitude: 20.84, longitude: 84.32 },
  { district: "Cuttack", state: "Odisha", latitude: 20.46, longitude: 85.88 },
  { district: "Deogarh", state: "Odisha", latitude: 21.54, longitude: 84.73 },
  { district: "Dhenkanal", state: "Odisha", latitude: 20.67, longitude: 85.6 },
  { district: "Gajapati", state: "Odisha", latitude: 19.2, longitude: 84.13 },
  { district: "Ganjam", state: "Odisha", latitude: 19.59, longitude: 84.35 },
  { district: "Jagatsinghpur", state: "Odisha", latitude: 20.26, longitude: 86.17 },
  { district: "Jajpur", state: "Odisha", latitude: 20.85, longitude: 86.34 },
  { district: "Jharsuguda", state: "Odisha", latitude: 21.85, longitude: 84.01 },
  { district: "Kalahandi", state: "Odisha", latitude: 19.91, longitude: 83.17 },
  { district: "Kandhamal", state: "Odisha", latitude: 20.18, longitude: 84.07 },
  { district: "Kendrapara", state: "Odisha", latitude: 20.5, longitude: 86.42 },
  { district: "Kendujhar", state: "Odisha", latitude: 21.63, longitude: 85.58 },
  { district: "Khordha", state: "Odisha", latitude: 20.18, longitude: 85.62 },
  { district: "Koraput", state: "Odisha", latitude: 18.81, longitude: 82.71 },
  { district: "Malkangiri", state: "Odisha", latitude: 18.35, longitude: 81.88 },
  { district: "Mayurbhanj", state: "Odisha", latitude: 21.94, longitude: 86.73 },
  { district: "Nabarangpur", state: "Odisha", latitude: 19.23, longitude: 82.55 },
  { district: "Nayagarh", state: "Odisha", latitude: 20.13, longitude: 85.1 },
  { district: "Nuapada", state: "Odisha", latitude: 20.8, longitude: 82.55 },
  { district: "Puri", state: "Odisha", latitude: 19.81, longitude: 85.85 },
  { district: "Rayagada", state: "Odisha", latitude: 19.17, longitude: 83.42 },
  { district: "Sambalpur", state: "Odisha", latitude: 21.47, longitude: 83.97 },
  { district: "Subarnapur", state: "Odisha", latitude: 20.8, longitude: 83.87 },
  { district: "Sundargarh", state: "Odisha", latitude: 22.12, longitude: 84.03 },

  // ─── PUNJAB (23 Districts) ─────────────────────────────
  { district: "Amritsar", state: "Punjab", latitude: 31.63, longitude: 74.87 },
  { district: "Barnala", state: "Punjab", latitude: 30.38, longitude: 75.55 },
  { district: "Bathinda", state: "Punjab", latitude: 30.21, longitude: 74.95 },
  { district: "Faridkot", state: "Punjab", latitude: 30.68, longitude: 74.76 },
  { district: "Fatehgarh Sahib", state: "Punjab", latitude: 30.64, longitude: 76.39 },
  { district: "Fazilka", state: "Punjab", latitude: 30.4, longitude: 74.03 },
  { district: "Ferozepur", state: "Punjab", latitude: 30.93, longitude: 74.61 },
  { district: "Gurdaspur", state: "Punjab", latitude: 32.04, longitude: 75.4 },
  { district: "Hoshiarpur", state: "Punjab", latitude: 31.53, longitude: 75.91 },
  { district: "Jalandhar", state: "Punjab", latitude: 31.33, longitude: 75.58 },
  { district: "Kapurthala", state: "Punjab", latitude: 31.38, longitude: 75.38 },
  { district: "Ludhiana", state: "Punjab", latitude: 30.9, longitude: 75.86 },
  { district: "Malerkotla", state: "Punjab", latitude: 30.53, longitude: 75.88 },
  { district: "Mansa", state: "Punjab", latitude: 29.99, longitude: 75.4 },
  { district: "Moga", state: "Punjab", latitude: 30.82, longitude: 75.17 },
  { district: "Muktsar", state: "Punjab", latitude: 30.47, longitude: 74.52 },
  { district: "Nawanshahr", state: "Punjab", latitude: 31.12, longitude: 76.12 },
  { district: "Pathankot", state: "Punjab", latitude: 32.27, longitude: 75.65 },
  { district: "Patiala", state: "Punjab", latitude: 30.34, longitude: 76.39 },
  { district: "Rupnagar", state: "Punjab", latitude: 30.97, longitude: 76.53 },
  { district: "Sangrur", state: "Punjab", latitude: 30.25, longitude: 75.84 },
  { district: "SAS Nagar", state: "Punjab", latitude: 30.7, longitude: 76.72 },
  { district: "Tarn Taran", state: "Punjab", latitude: 31.45, longitude: 74.93 },

  // ─── RAJASTHAN (50 Districts) ──────────────────────────
  { district: "Ajmer", state: "Rajasthan", latitude: 26.45, longitude: 74.64 },
  { district: "Alwar", state: "Rajasthan", latitude: 27.56, longitude: 76.63 },
  { district: "Banswara", state: "Rajasthan", latitude: 23.55, longitude: 74.44 },
  { district: "Baran", state: "Rajasthan", latitude: 25.1, longitude: 76.51 },
  { district: "Barmer", state: "Rajasthan", latitude: 25.75, longitude: 71.39 },
  { district: "Bharatpur", state: "Rajasthan", latitude: 27.22, longitude: 77.5 },
  { district: "Bhilwara", state: "Rajasthan", latitude: 25.35, longitude: 74.64 },
  { district: "Bikaner", state: "Rajasthan", latitude: 28.02, longitude: 73.31 },
  { district: "Bundi", state: "Rajasthan", latitude: 25.44, longitude: 75.64 },
  { district: "Chittorgarh", state: "Rajasthan", latitude: 24.88, longitude: 74.63 },
  { district: "Churu", state: "Rajasthan", latitude: 28.3, longitude: 74.97 },
  { district: "Dausa", state: "Rajasthan", latitude: 26.88, longitude: 76.34 },
  { district: "Dholpur", state: "Rajasthan", latitude: 26.7, longitude: 77.9 },
  { district: "Dungarpur", state: "Rajasthan", latitude: 23.84, longitude: 73.71 },
  { district: "Hanumangarh", state: "Rajasthan", latitude: 29.58, longitude: 74.32 },
  { district: "Jaipur", state: "Rajasthan", latitude: 26.92, longitude: 75.79 },
  { district: "Jaisalmer", state: "Rajasthan", latitude: 26.92, longitude: 70.91 },
  { district: "Jalore", state: "Rajasthan", latitude: 25.35, longitude: 72.62 },
  { district: "Jhalawar", state: "Rajasthan", latitude: 24.6, longitude: 76.17 },
  { district: "Jhunjhunu", state: "Rajasthan", latitude: 28.13, longitude: 75.4 },
  { district: "Jodhpur", state: "Rajasthan", latitude: 26.29, longitude: 73.02 },
  { district: "Karauli", state: "Rajasthan", latitude: 26.5, longitude: 77.02 },
  { district: "Kota", state: "Rajasthan", latitude: 25.18, longitude: 75.83 },
  { district: "Nagaur", state: "Rajasthan", latitude: 27.2, longitude: 73.74 },
  { district: "Pali", state: "Rajasthan", latitude: 25.77, longitude: 73.33 },
  { district: "Pratapgarh", state: "Rajasthan", latitude: 24.03, longitude: 74.78 },
  { district: "Rajsamand", state: "Rajasthan", latitude: 25.07, longitude: 73.88 },
  { district: "Sawai Madhopur", state: "Rajasthan", latitude: 26.02, longitude: 76.35 },
  { district: "Sikar", state: "Rajasthan", latitude: 27.61, longitude: 75.14 },
  { district: "Sirohi", state: "Rajasthan", latitude: 24.89, longitude: 72.86 },
  { district: "Sri Ganganagar", state: "Rajasthan", latitude: 29.91, longitude: 73.88 },
  { district: "Tonk", state: "Rajasthan", latitude: 26.17, longitude: 75.79 },
  { district: "Udaipur", state: "Rajasthan", latitude: 24.58, longitude: 73.71 },
  { district: "Anupgarh", state: "Rajasthan", latitude: 29.2, longitude: 73.2 },
  { district: "Balotra", state: "Rajasthan", latitude: 25.83, longitude: 72.24 },
  { district: "Beawar", state: "Rajasthan", latitude: 26.1, longitude: 74.32 },
  { district: "Deedwana-Kuchaman", state: "Rajasthan", latitude: 27.6, longitude: 74.6 },
  { district: "Dudu", state: "Rajasthan", latitude: 26.6, longitude: 75.3 },
  { district: "Gangapur City", state: "Rajasthan", latitude: 26.47, longitude: 76.73 },
  { district: "Jaipur Rural", state: "Rajasthan", latitude: 27.0, longitude: 75.9 },
  { district: "Jodhpur Rural", state: "Rajasthan", latitude: 26.4, longitude: 72.8 },
  { district: "Kekri", state: "Rajasthan", latitude: 25.97, longitude: 75.14 },
  { district: "Khairthal-Tijara", state: "Rajasthan", latitude: 27.6, longitude: 76.7 },
  { district: "Kotputli-Behror", state: "Rajasthan", latitude: 27.7, longitude: 76.2 },
  { district: "Neem Ka Thana", state: "Rajasthan", latitude: 27.7, longitude: 75.8 },
  { district: "Phalodi", state: "Rajasthan", latitude: 27.13, longitude: 72.37 },
  { district: "Salumbar", state: "Rajasthan", latitude: 24.1, longitude: 74.0 },
  { district: "Sanchore", state: "Rajasthan", latitude: 24.75, longitude: 71.78 },
  { district: "Shahpura", state: "Rajasthan", latitude: 27.4, longitude: 75.95 },
  { district: "Sujangarh", state: "Rajasthan", latitude: 27.7, longitude: 74.5 },

  // ─── SIKKIM (6 Districts) ─────────────────────────────
  { district: "East Sikkim", state: "Sikkim", latitude: 27.33, longitude: 88.62 },
  { district: "North Sikkim", state: "Sikkim", latitude: 27.9, longitude: 88.6 },
  { district: "South Sikkim", state: "Sikkim", latitude: 27.17, longitude: 88.35 },
  { district: "West Sikkim", state: "Sikkim", latitude: 27.3, longitude: 88.22 },
  { district: "Pakyong", state: "Sikkim", latitude: 27.22, longitude: 88.7 },
  { district: "Soreng", state: "Sikkim", latitude: 27.17, longitude: 88.12 },

  // ─── TAMIL NADU (38 Districts) ─────────────────────────
  { district: "Ariyalur", state: "Tamil Nadu", latitude: 11.14, longitude: 79.08 },
  { district: "Chengalpattu", state: "Tamil Nadu", latitude: 12.69, longitude: 79.98 },
  { district: "Chennai", state: "Tamil Nadu", latitude: 13.08, longitude: 80.27 },
  { district: "Coimbatore", state: "Tamil Nadu", latitude: 11.0, longitude: 76.96 },
  { district: "Cuddalore", state: "Tamil Nadu", latitude: 11.75, longitude: 79.77 },
  { district: "Dharmapuri", state: "Tamil Nadu", latitude: 12.13, longitude: 78.16 },
  { district: "Dindigul", state: "Tamil Nadu", latitude: 10.37, longitude: 77.97 },
  { district: "Erode", state: "Tamil Nadu", latitude: 11.34, longitude: 77.72 },
  { district: "Kallakurichi", state: "Tamil Nadu", latitude: 11.74, longitude: 78.96 },
  { district: "Kancheepuram", state: "Tamil Nadu", latitude: 12.83, longitude: 79.7 },
  { district: "Karur", state: "Tamil Nadu", latitude: 10.96, longitude: 78.08 },
  { district: "Krishnagiri", state: "Tamil Nadu", latitude: 12.52, longitude: 78.21 },
  { district: "Madurai", state: "Tamil Nadu", latitude: 9.92, longitude: 78.12 },
  { district: "Mayiladuthurai", state: "Tamil Nadu", latitude: 11.1, longitude: 79.65 },
  { district: "Nagapattinam", state: "Tamil Nadu", latitude: 10.77, longitude: 79.84 },
  { district: "Namakkal", state: "Tamil Nadu", latitude: 11.22, longitude: 78.17 },
  { district: "Nilgiris", state: "Tamil Nadu", latitude: 11.49, longitude: 76.73 },
  { district: "Perambalur", state: "Tamil Nadu", latitude: 11.23, longitude: 78.88 },
  { district: "Pudukkottai", state: "Tamil Nadu", latitude: 10.38, longitude: 78.82 },
  { district: "Ramanathapuram", state: "Tamil Nadu", latitude: 9.37, longitude: 78.83 },
  { district: "Ranipet", state: "Tamil Nadu", latitude: 12.93, longitude: 79.33 },
  { district: "Salem", state: "Tamil Nadu", latitude: 11.66, longitude: 78.15 },
  { district: "Sivagangai", state: "Tamil Nadu", latitude: 10.43, longitude: 78.49 },
  { district: "Tenkasi", state: "Tamil Nadu", latitude: 8.96, longitude: 77.31 },
  { district: "Thanjavur", state: "Tamil Nadu", latitude: 10.79, longitude: 79.14 },
  { district: "Theni", state: "Tamil Nadu", latitude: 10.01, longitude: 77.48 },
  { district: "Thoothukudi", state: "Tamil Nadu", latitude: 8.76, longitude: 78.14 },
  { district: "Tiruchirappalli", state: "Tamil Nadu", latitude: 10.8, longitude: 78.69 },
  { district: "Tirunelveli", state: "Tamil Nadu", latitude: 8.73, longitude: 77.7 },
  { district: "Tirupathur", state: "Tamil Nadu", latitude: 12.5, longitude: 78.57 },
  { district: "Tiruppur", state: "Tamil Nadu", latitude: 11.11, longitude: 77.35 },
  { district: "Tiruvallur", state: "Tamil Nadu", latitude: 13.14, longitude: 79.91 },
  { district: "Tiruvannamalai", state: "Tamil Nadu", latitude: 12.23, longitude: 79.07 },
  { district: "Tiruvarur", state: "Tamil Nadu", latitude: 10.77, longitude: 79.64 },
  { district: "Vellore", state: "Tamil Nadu", latitude: 12.92, longitude: 79.13 },
  { district: "Viluppuram", state: "Tamil Nadu", latitude: 11.94, longitude: 79.49 },
  { district: "Virudhunagar", state: "Tamil Nadu", latitude: 9.58, longitude: 77.96 },
  { district: "Kanyakumari", state: "Tamil Nadu", latitude: 8.09, longitude: 77.57 },

  // ─── TELANGANA (33 Districts) ──────────────────────────
  { district: "Adilabad", state: "Telangana", latitude: 19.67, longitude: 78.53 },
  { district: "Bhadradri Kothagudem", state: "Telangana", latitude: 17.55, longitude: 80.62 },
  { district: "Hyderabad", state: "Telangana", latitude: 17.38, longitude: 78.49 },
  { district: "Jagtial", state: "Telangana", latitude: 18.79, longitude: 78.91 },
  { district: "Jangaon", state: "Telangana", latitude: 17.73, longitude: 79.17 },
  { district: "Jayashankar Bhupalpally", state: "Telangana", latitude: 18.4, longitude: 79.9 },
  { district: "Jogulamba Gadwal", state: "Telangana", latitude: 16.23, longitude: 77.81 },
  { district: "Kamareddy", state: "Telangana", latitude: 18.32, longitude: 78.34 },
  { district: "Karimnagar", state: "Telangana", latitude: 18.44, longitude: 79.13 },
  { district: "Khammam", state: "Telangana", latitude: 17.25, longitude: 80.15 },
  { district: "Kumuram Bheem Asifabad", state: "Telangana", latitude: 19.36, longitude: 79.28 },
  { district: "Mahabubabad", state: "Telangana", latitude: 17.6, longitude: 80.0 },
  { district: "Mahabubnagar", state: "Telangana", latitude: 16.73, longitude: 77.99 },
  { district: "Mancherial", state: "Telangana", latitude: 18.87, longitude: 79.44 },
  { district: "Medak", state: "Telangana", latitude: 18.05, longitude: 78.26 },
  { district: "Medchal-Malkajgiri", state: "Telangana", latitude: 17.53, longitude: 78.53 },
  { district: "Mulugu", state: "Telangana", latitude: 18.2, longitude: 79.9 },
  { district: "Nagarkurnool", state: "Telangana", latitude: 16.48, longitude: 78.32 },
  { district: "Nalgonda", state: "Telangana", latitude: 17.05, longitude: 79.27 },
  { district: "Narayanpet", state: "Telangana", latitude: 16.74, longitude: 77.5 },
  { district: "Nirmal", state: "Telangana", latitude: 19.1, longitude: 78.35 },
  { district: "Nizamabad", state: "Telangana", latitude: 18.67, longitude: 78.09 },
  { district: "Peddapalli", state: "Telangana", latitude: 18.62, longitude: 79.38 },
  { district: "Rajanna Sircilla", state: "Telangana", latitude: 18.39, longitude: 78.83 },
  { district: "Rangareddy", state: "Telangana", latitude: 17.22, longitude: 78.28 },
  { district: "Sangareddy", state: "Telangana", latitude: 17.63, longitude: 78.09 },
  { district: "Siddipet", state: "Telangana", latitude: 18.1, longitude: 78.85 },
  { district: "Suryapet", state: "Telangana", latitude: 17.14, longitude: 79.63 },
  { district: "Vikarabad", state: "Telangana", latitude: 17.34, longitude: 77.9 },
  { district: "Wanaparthy", state: "Telangana", latitude: 16.36, longitude: 78.06 },
  { district: "Warangal", state: "Telangana", latitude: 17.97, longitude: 79.6 },
  { district: "Hanamkonda", state: "Telangana", latitude: 18.0, longitude: 79.58 },
  { district: "Yadadri Bhuvanagiri", state: "Telangana", latitude: 17.6, longitude: 78.95 },

  // ─── TRIPURA (8 Districts) ─────────────────────────────
  { district: "Dhalai", state: "Tripura", latitude: 23.84, longitude: 91.98 },
  { district: "Gomati", state: "Tripura", latitude: 23.53, longitude: 91.57 },
  { district: "Khowai", state: "Tripura", latitude: 24.07, longitude: 91.61 },
  { district: "North Tripura", state: "Tripura", latitude: 24.32, longitude: 92.03 },
  { district: "Sepahijala", state: "Tripura", latitude: 23.6, longitude: 91.2 },
  { district: "South Tripura", state: "Tripura", latitude: 23.28, longitude: 91.43 },
  { district: "Unakoti", state: "Tripura", latitude: 24.32, longitude: 92.1 },
  { district: "West Tripura", state: "Tripura", latitude: 23.83, longitude: 91.28 },

  // ─── UTTAR PRADESH (75 Districts) ──────────────────────
  { district: "Agra", state: "Uttar Pradesh", latitude: 27.18, longitude: 78.02 },
  { district: "Aligarh", state: "Uttar Pradesh", latitude: 27.88, longitude: 78.08 },
  { district: "Ambedkar Nagar", state: "Uttar Pradesh", latitude: 26.45, longitude: 82.7 },
  { district: "Amethi", state: "Uttar Pradesh", latitude: 26.15, longitude: 81.81 },
  { district: "Amroha", state: "Uttar Pradesh", latitude: 28.9, longitude: 78.47 },
  { district: "Auraiya", state: "Uttar Pradesh", latitude: 26.47, longitude: 79.51 },
  { district: "Ayodhya", state: "Uttar Pradesh", latitude: 26.8, longitude: 82.2 },
  { district: "Azamgarh", state: "Uttar Pradesh", latitude: 26.07, longitude: 83.19 },
  { district: "Baghpat", state: "Uttar Pradesh", latitude: 28.95, longitude: 77.22 },
  { district: "Bahraich", state: "Uttar Pradesh", latitude: 27.57, longitude: 81.6 },
  { district: "Ballia", state: "Uttar Pradesh", latitude: 25.76, longitude: 84.15 },
  { district: "Balrampur", state: "Uttar Pradesh", latitude: 27.43, longitude: 82.18 },
  { district: "Banda", state: "Uttar Pradesh", latitude: 25.48, longitude: 80.34 },
  { district: "Barabanki", state: "Uttar Pradesh", latitude: 26.93, longitude: 81.18 },
  { district: "Bareilly", state: "Uttar Pradesh", latitude: 28.37, longitude: 79.42 },
  { district: "Basti", state: "Uttar Pradesh", latitude: 26.8, longitude: 82.73 },
  { district: "Bhadohi", state: "Uttar Pradesh", latitude: 25.4, longitude: 82.57 },
  { district: "Bijnor", state: "Uttar Pradesh", latitude: 29.37, longitude: 78.14 },
  { district: "Budaun", state: "Uttar Pradesh", latitude: 28.04, longitude: 79.12 },
  { district: "Bulandshahr", state: "Uttar Pradesh", latitude: 28.41, longitude: 77.85 },
  { district: "Chandauli", state: "Uttar Pradesh", latitude: 25.27, longitude: 83.27 },
  { district: "Chitrakoot", state: "Uttar Pradesh", latitude: 25.2, longitude: 80.83 },
  { district: "Deoria", state: "Uttar Pradesh", latitude: 26.5, longitude: 83.78 },
  { district: "Etah", state: "Uttar Pradesh", latitude: 27.56, longitude: 78.66 },
  { district: "Etawah", state: "Uttar Pradesh", latitude: 26.78, longitude: 79.02 },
  { district: "Farrukhabad", state: "Uttar Pradesh", latitude: 27.39, longitude: 79.58 },
  { district: "Fatehpur", state: "Uttar Pradesh", latitude: 25.93, longitude: 80.81 },
  { district: "Firozabad", state: "Uttar Pradesh", latitude: 27.15, longitude: 78.39 },
  { district: "Gautam Buddha Nagar", state: "Uttar Pradesh", latitude: 28.57, longitude: 77.36 },
  { district: "Ghaziabad", state: "Uttar Pradesh", latitude: 28.66, longitude: 77.44 },
  { district: "Ghazipur", state: "Uttar Pradesh", latitude: 25.58, longitude: 83.58 },
  { district: "Gonda", state: "Uttar Pradesh", latitude: 27.13, longitude: 81.96 },
  { district: "Gorakhpur", state: "Uttar Pradesh", latitude: 26.76, longitude: 83.37 },
  { district: "Hamirpur", state: "Uttar Pradesh", latitude: 25.95, longitude: 80.15 },
  { district: "Hapur", state: "Uttar Pradesh", latitude: 28.73, longitude: 77.78 },
  { district: "Hardoi", state: "Uttar Pradesh", latitude: 27.39, longitude: 80.13 },
  { district: "Hathras", state: "Uttar Pradesh", latitude: 27.6, longitude: 78.05 },
  { district: "Jalaun", state: "Uttar Pradesh", latitude: 26.15, longitude: 79.34 },
  { district: "Jaunpur", state: "Uttar Pradesh", latitude: 25.75, longitude: 82.68 },
  { district: "Jhansi", state: "Uttar Pradesh", latitude: 25.45, longitude: 78.57 },
  { district: "Kannauj", state: "Uttar Pradesh", latitude: 27.06, longitude: 79.92 },
  { district: "Kanpur Dehat", state: "Uttar Pradesh", latitude: 26.4, longitude: 79.95 },
  { district: "Kanpur Nagar", state: "Uttar Pradesh", latitude: 26.45, longitude: 80.35 },
  { district: "Kasganj", state: "Uttar Pradesh", latitude: 27.81, longitude: 78.65 },
  { district: "Kaushambi", state: "Uttar Pradesh", latitude: 25.53, longitude: 81.37 },
  { district: "Kushinagar", state: "Uttar Pradesh", latitude: 26.74, longitude: 83.89 },
  { district: "Lakhimpur Kheri", state: "Uttar Pradesh", latitude: 27.95, longitude: 80.78 },
  { district: "Lalitpur", state: "Uttar Pradesh", latitude: 24.69, longitude: 78.42 },
  { district: "Lucknow", state: "Uttar Pradesh", latitude: 26.85, longitude: 80.95 },
  { district: "Maharajganj", state: "Uttar Pradesh", latitude: 27.12, longitude: 83.56 },
  { district: "Mahoba", state: "Uttar Pradesh", latitude: 25.29, longitude: 79.87 },
  { district: "Mainpuri", state: "Uttar Pradesh", latitude: 27.23, longitude: 79.02 },
  { district: "Mathura", state: "Uttar Pradesh", latitude: 27.49, longitude: 77.67 },
  { district: "Mau", state: "Uttar Pradesh", latitude: 25.94, longitude: 83.56 },
  { district: "Meerut", state: "Uttar Pradesh", latitude: 28.98, longitude: 77.71 },
  { district: "Mirzapur", state: "Uttar Pradesh", latitude: 25.15, longitude: 82.57 },
  { district: "Moradabad", state: "Uttar Pradesh", latitude: 28.83, longitude: 78.78 },
  { district: "Muzaffarnagar", state: "Uttar Pradesh", latitude: 29.47, longitude: 77.7 },
  { district: "Pilibhit", state: "Uttar Pradesh", latitude: 28.64, longitude: 79.81 },
  { district: "Pratapgarh", state: "Uttar Pradesh", latitude: 25.9, longitude: 81.95 },
  { district: "Prayagraj", state: "Uttar Pradesh", latitude: 25.43, longitude: 81.85 },
  { district: "Rae Bareli", state: "Uttar Pradesh", latitude: 26.23, longitude: 81.24 },
  { district: "Rampur", state: "Uttar Pradesh", latitude: 28.81, longitude: 79.03 },
  { district: "Saharanpur", state: "Uttar Pradesh", latitude: 29.97, longitude: 77.55 },
  { district: "Sambhal", state: "Uttar Pradesh", latitude: 28.59, longitude: 78.57 },
  { district: "Sant Kabir Nagar", state: "Uttar Pradesh", latitude: 26.79, longitude: 83.04 },
  { district: "Shahjahanpur", state: "Uttar Pradesh", latitude: 27.88, longitude: 79.91 },
  { district: "Shamli", state: "Uttar Pradesh", latitude: 29.45, longitude: 77.31 },
  { district: "Shravasti", state: "Uttar Pradesh", latitude: 27.5, longitude: 81.75 },
  { district: "Siddharthnagar", state: "Uttar Pradesh", latitude: 27.26, longitude: 83.0 },
  { district: "Sitapur", state: "Uttar Pradesh", latitude: 27.57, longitude: 80.68 },
  { district: "Sonbhadra", state: "Uttar Pradesh", latitude: 24.69, longitude: 83.07 },
  { district: "Sultanpur", state: "Uttar Pradesh", latitude: 26.27, longitude: 82.07 },
  { district: "Unnao", state: "Uttar Pradesh", latitude: 26.55, longitude: 80.49 },
  { district: "Varanasi", state: "Uttar Pradesh", latitude: 25.32, longitude: 83.01 },

  // ─── UTTARAKHAND (13 Districts) ────────────────────────
  { district: "Almora", state: "Uttarakhand", latitude: 29.6, longitude: 79.66 },
  { district: "Bageshwar", state: "Uttarakhand", latitude: 29.84, longitude: 79.77 },
  { district: "Chamoli", state: "Uttarakhand", latitude: 30.4, longitude: 79.33 },
  { district: "Champawat", state: "Uttarakhand", latitude: 29.34, longitude: 80.09 },
  { district: "Dehradun", state: "Uttarakhand", latitude: 30.32, longitude: 78.03 },
  { district: "Haridwar", state: "Uttarakhand", latitude: 29.95, longitude: 78.16 },
  { district: "Nainital", state: "Uttarakhand", latitude: 29.38, longitude: 79.45 },
  { district: "Pauri Garhwal", state: "Uttarakhand", latitude: 30.15, longitude: 78.78 },
  { district: "Pithoragarh", state: "Uttarakhand", latitude: 29.58, longitude: 80.22 },
  { district: "Rudraprayag", state: "Uttarakhand", latitude: 30.28, longitude: 79.0 },
  { district: "Tehri Garhwal", state: "Uttarakhand", latitude: 30.39, longitude: 78.48 },
  { district: "Udham Singh Nagar", state: "Uttarakhand", latitude: 28.99, longitude: 79.41 },
  { district: "Uttarkashi", state: "Uttarakhand", latitude: 30.73, longitude: 78.44 },

  // ─── WEST BENGAL (23 Districts) ────────────────────────
  { district: "Alipurduar", state: "West Bengal", latitude: 26.49, longitude: 89.53 },
  { district: "Bankura", state: "West Bengal", latitude: 23.24, longitude: 87.07 },
  { district: "Birbhum", state: "West Bengal", latitude: 23.86, longitude: 87.62 },
  { district: "Cooch Behar", state: "West Bengal", latitude: 26.33, longitude: 89.43 },
  { district: "Dakshin Dinajpur", state: "West Bengal", latitude: 25.5, longitude: 88.8 },
  { district: "Darjeeling", state: "West Bengal", latitude: 27.04, longitude: 88.26 },
  { district: "Hooghly", state: "West Bengal", latitude: 22.91, longitude: 88.39 },
  { district: "Howrah", state: "West Bengal", latitude: 22.59, longitude: 88.26 },
  { district: "Jalpaiguri", state: "West Bengal", latitude: 26.52, longitude: 88.73 },
  { district: "Jhargram", state: "West Bengal", latitude: 22.45, longitude: 86.99 },
  { district: "Kalimpong", state: "West Bengal", latitude: 27.06, longitude: 88.47 },
  { district: "Kolkata", state: "West Bengal", latitude: 22.57, longitude: 88.36 },
  { district: "Malda", state: "West Bengal", latitude: 25.01, longitude: 88.14 },
  { district: "Murshidabad", state: "West Bengal", latitude: 24.18, longitude: 88.27 },
  { district: "Nadia", state: "West Bengal", latitude: 23.47, longitude: 88.56 },
  { district: "North 24 Parganas", state: "West Bengal", latitude: 22.62, longitude: 88.44 },
  { district: "Paschim Bardhaman", state: "West Bengal", latitude: 23.25, longitude: 87.06 },
  { district: "Paschim Medinipur", state: "West Bengal", latitude: 22.42, longitude: 87.32 },
  { district: "Purba Bardhaman", state: "West Bengal", latitude: 23.23, longitude: 87.86 },
  { district: "Purba Medinipur", state: "West Bengal", latitude: 22.28, longitude: 87.92 },
  { district: "Purulia", state: "West Bengal", latitude: 23.33, longitude: 86.37 },
  { district: "South 24 Parganas", state: "West Bengal", latitude: 22.17, longitude: 88.43 },
  { district: "Uttar Dinajpur", state: "West Bengal", latitude: 25.86, longitude: 88.17 },

  // ─── UNION TERRITORIES ─────────────────────────────────
  // Delhi
  { district: "Central Delhi", state: "Delhi", latitude: 28.65, longitude: 77.23 },
  { district: "East Delhi", state: "Delhi", latitude: 28.63, longitude: 77.3 },
  { district: "New Delhi", state: "Delhi", latitude: 28.61, longitude: 77.21 },
  { district: "North Delhi", state: "Delhi", latitude: 28.73, longitude: 77.2 },
  { district: "North East Delhi", state: "Delhi", latitude: 28.69, longitude: 77.27 },
  { district: "North West Delhi", state: "Delhi", latitude: 28.74, longitude: 77.08 },
  { district: "Shahdara", state: "Delhi", latitude: 28.67, longitude: 77.29 },
  { district: "South Delhi", state: "Delhi", latitude: 28.53, longitude: 77.21 },
  { district: "South East Delhi", state: "Delhi", latitude: 28.55, longitude: 77.26 },
  { district: "South West Delhi", state: "Delhi", latitude: 28.56, longitude: 77.08 },
  { district: "West Delhi", state: "Delhi", latitude: 28.66, longitude: 77.1 },

  // Jammu & Kashmir
  { district: "Anantnag", state: "Jammu & Kashmir", latitude: 33.73, longitude: 75.15 },
  { district: "Bandipora", state: "Jammu & Kashmir", latitude: 34.42, longitude: 74.66 },
  { district: "Baramulla", state: "Jammu & Kashmir", latitude: 34.2, longitude: 74.34 },
  { district: "Budgam", state: "Jammu & Kashmir", latitude: 33.93, longitude: 74.72 },
  { district: "Doda", state: "Jammu & Kashmir", latitude: 33.15, longitude: 75.55 },
  { district: "Ganderbal", state: "Jammu & Kashmir", latitude: 34.23, longitude: 74.78 },
  { district: "Jammu", state: "Jammu & Kashmir", latitude: 32.73, longitude: 74.87 },
  { district: "Kathua", state: "Jammu & Kashmir", latitude: 32.38, longitude: 75.52 },
  { district: "Kishtwar", state: "Jammu & Kashmir", latitude: 33.31, longitude: 75.77 },
  { district: "Kulgam", state: "Jammu & Kashmir", latitude: 33.64, longitude: 75.02 },
  { district: "Kupwara", state: "Jammu & Kashmir", latitude: 34.53, longitude: 74.27 },
  { district: "Poonch", state: "Jammu & Kashmir", latitude: 33.77, longitude: 74.09 },
  { district: "Pulwama", state: "Jammu & Kashmir", latitude: 33.87, longitude: 74.9 },
  { district: "Rajouri", state: "Jammu & Kashmir", latitude: 33.38, longitude: 74.31 },
  { district: "Ramban", state: "Jammu & Kashmir", latitude: 33.24, longitude: 75.24 },
  { district: "Reasi", state: "Jammu & Kashmir", latitude: 33.08, longitude: 74.83 },
  { district: "Samba", state: "Jammu & Kashmir", latitude: 32.55, longitude: 75.12 },
  { district: "Shopian", state: "Jammu & Kashmir", latitude: 33.72, longitude: 74.83 },
  { district: "Srinagar", state: "Jammu & Kashmir", latitude: 34.08, longitude: 74.79 },
  { district: "Udhampur", state: "Jammu & Kashmir", latitude: 32.92, longitude: 75.14 },

  // Ladakh
  { district: "Kargil", state: "Ladakh", latitude: 34.55, longitude: 76.13 },
  { district: "Leh", state: "Ladakh", latitude: 34.17, longitude: 77.58 },

  // Chandigarh
  { district: "Chandigarh", state: "Chandigarh", latitude: 30.74, longitude: 76.79 },

  // Puducherry
  { district: "Puducherry", state: "Puducherry", latitude: 11.93, longitude: 79.83 },
  { district: "Karaikal", state: "Puducherry", latitude: 10.92, longitude: 79.84 },
  { district: "Mahe", state: "Puducherry", latitude: 11.7, longitude: 75.54 },
  { district: "Yanam", state: "Puducherry", latitude: 16.73, longitude: 82.22 },

  // Andaman & Nicobar
  { district: "Nicobar", state: "Andaman & Nicobar", latitude: 7.03, longitude: 93.79 },
  { district: "North and Middle Andaman", state: "Andaman & Nicobar", latitude: 12.67, longitude: 92.77 },
  { district: "South Andaman", state: "Andaman & Nicobar", latitude: 11.62, longitude: 92.73 },

  // Dadra and Nagar Haveli and Daman & Diu
  { district: "Dadra and Nagar Haveli", state: "Dadra and Nagar Haveli and Daman & Diu", latitude: 20.27, longitude: 73.01 },
  { district: "Daman", state: "Dadra and Nagar Haveli and Daman & Diu", latitude: 20.41, longitude: 72.84 },
  { district: "Diu", state: "Dadra and Nagar Haveli and Daman & Diu", latitude: 20.71, longitude: 70.98 },

  // Lakshadweep
  { district: "Lakshadweep", state: "Lakshadweep", latitude: 10.57, longitude: 72.64 },

  // ─── NEWLY NOTIFIED OFFICIAL DISTRICTS (Bringing National Grid to 802 Districts) ───
  // Ladakh (2024 Gazette Notifications)
  { district: "Zanskar", state: "Ladakh", latitude: 33.49, longitude: 76.88 },
  { district: "Drass", state: "Ladakh", latitude: 34.43, longitude: 75.76 },
  { district: "Sham", state: "Ladakh", latitude: 34.25, longitude: 77.10 },
  { district: "Nubra", state: "Ladakh", latitude: 34.69, longitude: 77.56 },
  { district: "Changthang", state: "Ladakh", latitude: 33.90, longitude: 78.70 },

  // Madhya Pradesh (2023-2024 Gazette)
  { district: "Mauganj", state: "Madhya Pradesh", latitude: 24.68, longitude: 81.87 },
  { district: "Maihar", state: "Madhya Pradesh", latitude: 24.27, longitude: 80.76 },
  { district: "Pandhurna", state: "Madhya Pradesh", latitude: 21.60, longitude: 78.53 },

  // Punjab (23rd District)
  { district: "Malerkotla", state: "Punjab", latitude: 30.53, longitude: 75.89 },

  // Assam (Recent Reorganizations)
  { district: "Tamulpur", state: "Assam", latitude: 26.63, longitude: 91.57 },
  { district: "Bajali", state: "Assam", latitude: 26.49, longitude: 91.24 },
  { district: "Hojai", state: "Assam", latitude: 26.00, longitude: 92.86 },
  { district: "Biswanath", state: "Assam", latitude: 26.73, longitude: 93.15 },

  // Chhattisgarh (Recent Reorganizations)
  { district: "Sakti", state: "Chhattisgarh", latitude: 21.96, longitude: 82.96 },
  { district: "Sarangarh-Bilaigarh", state: "Chhattisgarh", latitude: 21.59, longitude: 83.08 },
  { district: "Mohla-Manpur", state: "Chhattisgarh", latitude: 20.66, longitude: 80.74 },
  { district: "Manendragarh-Chirmiri-Bharatpur", state: "Chhattisgarh", latitude: 23.21, longitude: 82.20 },
  { district: "Khairagarh-Chhuikhadan-Gandai", state: "Chhattisgarh", latitude: 21.42, longitude: 80.98 },
];
